Added Indonesian Translate
xpple/SeedMapper pull request #27
Opened 2021-08-13 03:22 UTC by barraIhsan

Added Indonesian (`id_id.json`) Translate

2021-08-14 11:33 UTC, xpple requested changes
Thank you! Just one little thing :).

2021-08-14 11:33 UTC, xpple commented on src/main/resources/assets/seedmapper/lang/id_id.json
> +  "command.config.getSeed.null": "\"benih\" adalah null",
There should be a `.` here.

2021-08-15 02:27 UTC, barraIhsan commented on src/main/resources/assets/seedmapper/lang/id_id.json
> +  "command.config.getSeed.null": "\"benih\" adalah null",
In line 19?

2021-08-15 10:09 UTC, xpple commented on src/main/resources/assets/seedmapper/lang/id_id.json
> +  "command.config.getSeed.null": "\"benih\" adalah null",
Yep.

2021-08-15 23:15 UTC, barraIhsan commented on src/main/resources/assets/seedmapper/lang/id_id.json
> +  "command.config.getSeed.null": "\"benih\" adalah null",
ok

2021-08-15 23:16 UTC, barraIhsan commented on src/main/resources/assets/seedmapper/lang/id_id.json
> +  "command.config.getSeed.null": "\"benih\" adalah null",
Done

2021-08-15 23:31 UTC, xpple approved these changes

2021-08-15 23:31 UTC, merged

2021-08-15 23:32 UTC, xpple commented
Thank you!